### ISSUE TITLE
necessity of reserved memory in global memory pool

### ISSUE THREAD

**Issue by davidklaftenegger** [etascale/argodsm#22]
Currently at https://github.com/etascale/argodsm/blob/bdda067df87645bb683c8595d7515689db2f06ac/src/mempools/global_mempool.hpp#L52

The global memory pool unconditionally adds some memory "for internal use", but it is unclear what this memory is used for, and whether this is actually needed.

The notorious corner case would be a setup where ArgoDSM only requests to handle a single page, which is not currently tested for.

**Comment by lundgren87** [comment]
This issue is further complicated in argo_initialize:
https://github.com/etascale/argodsm/blob/ef644145ad85955cb229b962b0f5e6445349bb94/src/backend/mpi/swdsm.cpp#L1013-L1022
**Due to the memory added by the global memory pool**, this if-clause will trigger even for properly chosen ArgoDSM sizes (divisible by `pagesize*CACHELINE*numtasks, for numtasks>1`), and the requested `argo_size `will in such cases be `4096+argo_size+pagesize*CACHELINE*(numtasks-1)`.

This is (possibly?) again altered again in argo_initialize:
https://github.com/etascale/argodsm/blob/ef644145ad85955cb229b962b0f5e6445349bb94/src/backend/mpi/swdsm.cpp#L1086-L1089
I would argue that this is very confusing for a user who requests a well calculated `argo_size` in order to ensure efficient distribution of data, but ends up with hidden misalignments both before and after the requested argo_size.

**An example** allocation (very small for clarity) for four ArgoDSM nodes with the user intending to utilize all allocated ArgoDSM memory:
```
argo_size = 4096*16; //16 pages
cache_size = argo_size;
argo::init(argo_size, cache_size);
```
The expected outcome of pages per node _(argo_size=65536)_:
| page 0-3 | page 4-7 | page 8-11 | page 12-15 |

The actual outcome _(argo_size=81920)_:
| page 0-4 | page 5-9 | page 10-14 | page 15-19 |
where pages 0 and 17-19 would likely be empty, with user data allocated on pages 1-16 (4, 5, 5, 2 pages per nodes).
